version: "3.7"
services:
  # mysql数据库
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "Pwd123Pwd"
      MYSQL_USER: "tester"
      MYSQL_PASS: "123456"
    volumes:
      - ~/0xStock-db/data:/var/lib/mysql
      - ~/0xStock-db/migrations:/mysql/migrations
